version: "3.9"
services:
  web:
    build: .
    container_name: thriftly-react
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    stdin_open: true
    tty: true
